Env: dev
Dev:
  CookieHost: 192.168.1.129
  CookieSecure: false
  HttpOnly: false
  CorsHost: http://192.168.1.129:5173
  FrontUrl: http://192.168.1.129:5173
Prod:
  CookieHost: trainwithvocablo.com
  CookieSecure: true
  HttpOnly: true
  CorsHost: https://vocablo.com
  FrontUrl: https://vocablo.com
IP: 0.0.0.0
Port: 8080
JwtKey: vocablo258SECRETkey
Mail:
  User: viladevapps@gmail.com
  Pass: iabn dhoj wpyc zzwu
  SmtpHost: smtp.gmail.com
  SmtpPort: 587
  Texts:
    ValidateEmail:
      Subject: Validation code
      Body: "You can use this code to validate your account: %s"
    ResetPassword:
      Subject: Reset password code
      Body: "You can use this code to reset your password: %s"
DB:
  Port: 5436
  Host: localhost
  User: user
  Pass: password
  DB: database
