Env: prod
Dev:
  CookieHost: 192.168.1.129
  CookieSecure: false
  HttpOnly: false
  CorsHost: http://192.168.1.129:5173
  FrontUrl: http://192.168.1.129:5173
Prod:
  CookieHost: vocablo.dviladev.com
  CookieSecure: true
  HttpOnly: true
  CorsHost: https://vocablo.dviladev.com
  FrontUrl: https://vocablo.dviladev.com
IP: 0.0.0.0
Port: 8080
JwtKey: vocablosecret
Mail:
  User: viladevapps@gmail.com
  SmtpHost: smtp.gmail.com
  SmtpPort: 587
  Texts:
    ValidateEmail:
      Subject: Validation code
      Body: "You can use this code to validate your Vocablo account: %s"
    ResetPassword:
      Subject: Reset password code
      Body: "You can use this code to reset your Vocablo password: %s"
DB:
  Port: 5432
  Host: db
  User: root
  Pass: 123456
  DB: vocablo
