services:
  db:
    image: "postgres:16-alpine"
    environment:
      - "POSTGRES_DB=vocablo"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_USER=root"
    volumes:
      - db-volume:/data/db
  api: 
    image: vocablo-api:latest
    environment:
      DB_PASS: ${DB_PASS}
      MAIL_PASS: ${MAIL_PASS}
      JWT_SECRET: ${JWT_SECRET}
    restart: always
    ports:
      - "8084:8080"
    depends_on:
      - db
      
volumes:
  db-volume:
