version: '3.3'

services:
  db:
    image: "postgres:16-alpine"
    environment:
      - "POSTGRES_DB=${DB_DB}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_USER=${DB_USER}"
    volumes:
      - db:/data/db  
  api: 
    image: vocablo-api:latest
    restart: always
    ports:
      - "8084:8080"
    depends_on:
      - db
      
volumes:
  db-volume:
