services:
  db:
    image: "postgres:16-alpine"
    environment:
      - "POSTGRES_DB=${DB_DB}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_USER=${DB_USER}"
    ports:
      - "5436:5432"
    volumes:
      - db:/data/db
  # api:
  #   image: appname-api:latest
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
volumes:
  db:
